### ISSUE TITLE
Consider adding support for S?CSS generation ecosystem

### ISSUE THREAD

**Issue by EvaSDK** [calmjs/calmjs#28]
I was wondering if this was part of the roadmap at some point as doing any web application development  using Django, Flask, etc requires both js and css. So far I found no satisfying way to hook everything together in setuptools. Various solutions keep some spots of the whole toolchain out of the scope for some reason which makes none of them satisfactory

**Comment by metatoaster** [comment]
While the roadmap for Sass and the like isn't explicitly written down anywhere publicly yet, I definite have been thinking about how to go about it. The preliminary idea is that a separate package will be provided to interface with some library (likely one of the sass libraries for Python), and create a new registry for aggregating the sass files.  However, managing CSS is, in a way, more complicated than JS because developers of the dependent packages may wish to stub out even more style rules, thus it won't just be a straightforward dependency resolution through the standard package dependency graph and blindly pick every CSS file found.  The other complication is that I want to create a system that isn't just tightly coupled to that _one_ tool, but also make it possible for integration for users/developers that may want to use webpack (through the [calmjs.webpack](https://github.com/calmjs/calmjs.webpack) package, for instance).

An example on how dependent packages can reuse/extend the calmjs registry system (which is extension on top of setuptools/entry points) is [nunja](https://github.com/calmjs/nunja). As part of its functionality, it exposes the registered Jinja2 templates from a Python package through a [custom registry subclass](https://github.com/calmjs/nunja/blob/fe015c947db038ca488cbf09db51919054bde372/src/nunja/registry.py#L79).  So a similar concept may be done for exposing .scss files for conversion/bundling into a css file.

**Comment by metatoaster** [comment]
The package [`calmjs.sassy`](https://pypi.org/project/calmjs.sassy/) is released and available on PyPI; it provides a similar registry system for JavaScript source files as this base package for the basic generic support framework.  It also provide the base classes that can be extended to integrate with actual tools that consume them. Included with this first release, a default implementation that links with [`libsass-python`](https://sass.github.io/libsass-python/) is provided.  Please refer to the linked page (which is on PyPI) for the complete details.

If the current offering is unsatisfactory and/or issues were found, please file issues directly relevant to the sassy css integration to the [`calmjs.sassy` issue tracker](https://github.com/calmjs/calmjs.sassy/issues), while other issues directly related to the framework should be filed on the tracker for this package.

**Comment by EvaSDK** [comment]
I'll give it a look asap, thanks for your work.
