### ISSUE TITLE
How to know calmjs version

### ISSUE THREAD

**Issue by prrvchr** [calmjs/calmjs#68]
Hi all,

I'm trying to get the calmjs version installed.
Normally this is possible by reading the `__version__` attribute.
How to do it with calmjs.

**Comment by metatoaster** [comment]
The `calmjs` package does not offer the `__version__` attribute because it's provided also as a namespace package and thus it's literally impossible to do in Python.  Even all subpackages (i.e. `calmjs.parse`) do not offer this simply because I find this to be an anti-pattern when it is in fact package metadata, so please refer to [this stackoverflow thread](https://stackoverflow.com/questions/20180543/how-do-i-check-the-versions-of-python-modules) for a very detailed discussion on everything about this topic.

Anyway, [this specific answer](https://stackoverflow.com/a/32965521) provide the code that you need to achieve this for any Python packages that have been installed properly.
